### ISSUE TITLE
Date & Time Bypass Issue

### ISSUE THREAD

**Issue by dedsec1911** [pzienowicz/Trialer#1]
It can easily be bypassed by manipulating the Date and Time in the Settings. Do you have any solution for that ?

**Comment by pzienowicz** [comment]
@dedsec1911 yes - you can implement own validator which is going to check datetime on some external server and then validate if datetime passed.
I have not created validator like this - some apps don't require internet connection. But if it is good solution for you, we can consider implementing it - or just do it and open PR :)

**Comment by dedsec1911** [comment]
Thanks for your reply @pzienowicz but I just need an example of it to understand that how it works, so it would be great if you could implement that.

**Comment by pzienowicz** [comment]
@dedsec1911,

here simple pseudocode:
```
class ServerDateValidator(private val staticDate: Date) : ValidatorInterface {

    override fun valid(context: Context): Boolean {
        date = getDateFromServer()
        if(staticDate.before(date)) {
            return false
        }

        return true
    }

    fun getDateFromServer() {
        //magic stuff here - just get current date from some server
    }
}
````

I can do it when I find some free time - it's hard to guess when :)

**Comment by pzienowicz** [comment]
Date you can get using this API:
http://worldclockapi.com/api/json/est/now

**Comment by dedsec1911** [comment]
Thanks I appreciate that, but I need the code in Java !

**Comment by pzienowicz** [comment]
I believe you can convert this code to java :)
I am not going to add this kind of validator because I don't want to add any dependencies to REST libraries.
